# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-15

    env:
      XCODE_VERSION: 16.3

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "${{ env.XCODE_VERSION }}"
    - run: npm install --no-package-lock
      name: Install dev dependencies
    - run: npm run build
      name: Run build
    - run: npm run test
      name: Run test

    # building WDA packages
    - name: Building iOS
      run: sh $GITHUB_WORKSPACE/Scripts/ci/build-real.sh
      env:
        DERIVED_DATA_PATH: appium_wda_ios
        SCHEME: WebDriverAgentRunner
        DESTINATION: generic/platform=iOS
        WD: appium_wda_ios/Build/Products/Debug-iphoneos
        ZIP_PKG_NAME: WebDriverAgentRunner-Runner.zip
    - name: Building tvOS
      run: sh $GITHUB_WORKSPACE/Scripts/ci/build-real.sh
      env:
        DERIVED_DATA_PATH: appium_wda_tvos
        SCHEME: WebDriverAgentRunner_tvOS
        DESTINATION: generic/platform=tvOS
        WD: appium_wda_tvos/Build/Products/Debug-appletvos
        ZIP_PKG_NAME: WebDriverAgentRunner_tvOS-Runner.zip

    # release tasks
    - run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      name: Release

